### ISSUE TITLE
autocomplete

### ISSUE THREAD

**Issue by tmos** [stevielkim/weather-wunderground#2]
Hi,
after few days of hard work, I finnaly make it for autocompletion, so I share my code with you :)

```
//autocomplete
function autocomplete(typed){
    if (typed.length > 3) {
        getPossibleCities(typed);
    }
}
function getPossibleCities(cityLetters) {
    var request = "http://autocomplete.wunderground.com/aq?query="+cityLetters+"&cb=?";
    $.ajax({
        url : request,
        dataType : "jsonp",
        success : function(parsed_json) {
            display(parsed_json);
        },
        // error: function (xhr, ajaxOptions, thrownError) {
        //  console.log(xhr.status);
        //  console.log(thrownError);
        // }
    });
}

function display(json) {
}
```

I'm still working on the display part, but it shouldn't be the hardest part.

Hope it will help you :)

**Comment by tmos** [comment]
Me again, I juste made it to display json on the page, here is my code (put it inside the display function):

```
$.each(json, function(i,location){
        propositions = "";
        for (i = 0; i <= maxPropositionsToDisplay ; i++) {
            if (location[i] == undefined)
                break;
            propositions += ('<p>' + location[i].name +'</p>');
        };
        $("#yourDiv").html(propositions)
    });
```

I personnaly use html5 data attributes to set informations to each element for a later use.

**Comment by stevielkim** [comment]
Awesome thanks! I'm going to spend some time refactoring the code soon - make it more modular like I did with the app.js version that gets users input

**Comment by stevielkim** [comment]
Hey @tmos if you want to fork it and add your code to select.js you can do that, I've slowly been focusing on the app.js version and since you already did the work, you should get credit for it! After you fork the change, you can do a pull request, I'll quickly review and then merge it in. (If you want to do that)

**Comment by tmos** [comment]
Thanks for the proposition :)
I made my pull request here : https://github.com/StephanieKim/weather-wunderground/pull/3
As said in the comment, I let the computing of the result as is.

Thanks for your code, it helped me a lot, It is normal to give you some lines back :)

**Comment by stevielkim** [comment]
Closing this without merging - not compatible with codebase as it is now
